services:
    cdn77.tracy_blue_screen.blue_screen.console_blue_screen_error_listener:
        class: Cdn77\TracyBlueScreenBundle\BlueScreen\ConsoleBlueScreenErrorListener
        arguments:
            - '@cdn77.tracy_blue_screen.tracy.logger'
            - '@cdn77.tracy_blue_screen.tracy.blue_screen'
            - '%cdn77.tracy_blue_screen.console.log_directory%'
            - '%cdn77.tracy_blue_screen.console.browser%'
        tags:
            -
                name: kernel.event_listener
                event: console.error
                priority: '%cdn77.tracy_blue_screen.console.listener_priority%'
