services:
    cdn77.tracy_blue_screen.blue_screen.controller_blue_screen_exception_listener:
        class: Cdn77\TracyBlueScreenBundle\BlueScreen\ControllerBlueScreenExceptionListener
        arguments:
            - '@cdn77.tracy_blue_screen.tracy.blue_screen'
        tags:
            -
                name: kernel.event_listener
                event: kernel.exception
                priority: '%cdn77.tracy_blue_screen.controller.listener_priority%'
