services:
    cdn77.tracy_blue_screen.tracy.blue_screen: '@cdn77.tracy_blue_screen.tracy.blue_screen.default'

    cdn77.tracy_blue_screen.tracy.blue_screen.default:
        class: Tracy\BlueScreen
        factory: [Cdn77\TracyBlueScreenBundle\BlueScreen\BlueScreenFactory, create]
        arguments:
            - '%cdn77.tracy_blue_screen.blue_screen.collapse_paths%'
        public: false

    cdn77.tracy_blue_screen.tracy.logger: '@cdn77.tracy_blue_screen.tracy.logger.default'

    cdn77.tracy_blue_screen.tracy.logger.default:
        class: Tracy\Logger
        factory: [Tracy\Debugger, getLogger]
        public: false
